In [68]:
import numpy

def simplereg(x,y):
    
    xx =[]
    xy =[]
    for i in range(len(x)):
        xx.append(pow((x[i]-numpy.mean(x)),2))
        xy.append((x[i]-numpy.mean(x))*(y[i]-numpy.mean(y)))
        
    
    xx = sum(xx);xy=sum(xy)
    b1 = xy/xx
    b0 = numpy.mean(y)-b1*numpy.mean(x)
    return  b0,b1



a =numpy.array([[1,2,3],[4,5,6],[7,8,9]])
b =numpy.array([10,11,12])
print(a)
print(numpy.vstack([a,b]))
print(a)

print(numpy.hstack([a,b]))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: all the input arrays must have same number of dimensions